<?php 
session_start();
header('Content-type: text/json;charset=utf-8');
include_once 'include/config.php';
website_close();
website_deny();
$uid = $_SESSION['uid'];
$callback = $_GET['callback'];
include_once 'database/mysql.config.php';
include_once 'common/logintu.php';
$md = date('m-d');
sessionNum($uid, 4, $callback);
$zq = $zq_ds = $zq_gq = $zq_sbc = $zq_sbbd = $zq_bd = $zq_rqs = $zq_bqc = $zq_jg = 0;
$zqzc = $zqzc_ds = $zqzc_sbc = $zqzc_sbbd = $zqzc_bd = $zqzc_rqs = $zqzc_bqc = 0;
$lm = $lm_ds = $lm_dj = $lm_gq = $lm_jg = 0;
$lmzc = $lmzc_ds = $lmzc_dj = 0;
$wq = $wq_ds = $wq_bd = $wq_jg = 0;
$pq = $pq_ds = $pq_bd = $pq_jg = 0;
$bq = $bq_ds = $bq_zdf = $bq_jg = 0;
$jr = $jr_jr = $jr_jg = 0;
$gj = $gj_gj = $gj_jg = 0;
$tz_money = $user_num = $user_money = 0;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match  WHERE Match_Type=1 AND Match_CoverDate>now() AND Match_Date=:Match_Date and Match_HalfId is not null';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zq_ds = $stmt->fetchColumn();
include_once 'cache/zqgq.php';
if (20 < (time() - $lasttime)){
	$zq_gq = 0;
}else{
	$zq_gq = count($zqgq);
}

$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_Type=1 and match_date=:match_date AND Match_CoverDate>now() and (Match_BHo+Match_BAo<>0 or Match_Bdpl+Match_Bxpl<>0) and Match_IsShowb=1';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zq_sbc = $stmt->fetchColumn();
$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where match_date=:match_date and  Match_CoverDate>now() and Match_Hr_Bd10>0';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zq_sbbd = $stmt->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_Type=1 and Match_IsShowbd=1 and  Match_CoverDate>now() and Match_Bd21>0';
$query = $mydata1_db->query($sql);
$zq_bd = $query->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_Type=1 and Match_IsShowt=1 and Match_Total01Pl>0 AND Match_CoverDate>now()';
$query = $mydata1_db->query($sql);
$zq_rqs = $query->fetchColumn();
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_CoverDate>now() and Match_BqMM>0 and Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zq_bqc = $stmt->fetchColumn();
$params = array(':match_Date' => $md);
$sql = 'SELECT id FROM mydata4_db.Bet_Match where match_Date=:match_Date and (MB_Inball is not null or MB_Inball_HR is not NULL) and (match_js=1 or match_sbjs=1) and Match_Guest not like \'%上半%\' group by match_master';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zq_jg = $stmt->rowCount();
$zq = $zq_ds + $zq_gq + $zq_sbc + $zq_sbbd + $zq_bd + $zq_rqs + $zq_bqc + $zq_jg;
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match WHERE Match_Type=0 AND Match_CoverDate>now()';
$query = $mydata1_db->query($sql);
$zqzc_ds = $query->fetchColumn();
$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_CoverDate>now() and match_date!=:match_date and (Match_BHo+Match_BAo<>0 or Match_Bdpl+Match_Bxpl<>0) and Match_IsShowb=1';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zqzc_sbc = $stmt->fetchColumn();
$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where match_date!=:match_date and Match_CoverDate>now() and Match_Hr_Bd10>0';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zqzc_sbbd = $stmt->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_Type=0 and Match_IsShowbd=1 and   Match_CoverDate>now() and Match_Bd21>0';
$query = $mydata1_db->query($sql);
$zqzc_bd = $query->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match where Match_Type=0 and Match_IsShowt=1 AND Match_CoverDate>now() and Match_Total01Pl>0';
$query = $mydata1_db->query($sql);
$zqzc_rqs = $query->fetchColumn();
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.Bet_Match WHERE Match_Date<>:Match_Date and Match_CoverDate>now() and Match_BqMM>0';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$zqzc_bqc = $stmt->fetchColumn();
$zqzc = $zqzc_ds + $zqzc_sbc + $zqzc_sbbd + $zqzc_bd + $zqzc_rqs + $zqzc_bqc;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.lq_match WHERE Match_CoverDate>now() AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$lm_ds = $stmt->fetchColumn();
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.lq_match WHERE Match_Type=3 AND Match_CoverDate>=now() AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$lm_dj = $stmt->fetchColumn();
$params = array(':match_Date' => $md);
$sql = 'SELECT id FROM mydata4_db.lq_match WHERE MB_Inball_OK is not null and  match_Date=:match_Date and match_js=1 and Match_Guest not like \'% - (%\' group by match_master';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$lm_jg = $stmt->rowCount();
include_once 'cache/lqgq.php';
if (20 < (time() - $lasttime)){
	$lm_gq = 0;
}else{
	$lm_gq = count($lqgq);
}
$lm = $lm_ds + $lm_gq + $lm_jg;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.lq_match WHERE Match_CoverDate>now() AND Match_Date<>:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$lmzc_ds = $stmt->fetchColumn();
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.lq_match WHERE Match_Type=3 AND Match_CoverDate>now() AND Match_Date<>:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$$lmzc_dj = $stmt->fetchColumn();
$lmzc = $lmzc_ds;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.tennis_match WHERE Match_Type=1 AND Match_CoverDate>now() AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$wq_ds = $stmt->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.tennis_match where Match_Type=10 and Match_CoverDate>now() and Match_Bd21>0';
$query = $mydata1_db->query($sql);
$wq_bd = $query->fetchColumn();
$params = array(':match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.tennis_match where MB_Inball is not null and  match_Date=:match_Date and match_js=1';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$wq_jg = $stmt->fetchColumn();
$wq = $wq_ds + $wq_bd + $wq_jg;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM  mydata4_db.volleyball_match WHERE Match_Type=1 AND Match_CoverDate>now() AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$pq_ds = $stmt->fetchColumn();
$sql = 'SELECT count(*) as s FROM mydata4_db.volleyball_match where Match_Type=10 and Match_CoverDate>now()';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$pq_bd = $stmt->fetchColumn();
$params = array(':match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.volleyball_match where MB_Inball is not null and  match_Date=:match_Date and match_js=1';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$pq_jg = $stmt->fetchColumn();
$pq = $pq_ds + $pq_bd + $pq_jg;
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.baseball_match WHERE Match_Type=1 AND Match_CoverDate>now() AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$bq_ds = $stmt->fetchColumn();
$params = array(':Match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.baseball_match WHERE Match_Type=1 AND Match_CoverDate>now() and Match_BzM>0 AND Match_Date=:Match_Date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$bq_zdf = $stmt->fetchColumn();
$params = array(':match_Date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.baseball_match WHERE MB_Inball is not null and  match_Date=:match_Date and match_js=1';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$bq_jg = $stmt->fetchColumn();
$bq = $bq_ds + $bq_zdf + $bq_jg;
$sql = 'SELECT count(*) as s FROM mydata4_db.t_guanjun WHERE Match_CoverDate>now() and x_result is null and match_type=1';
$query = $mydata1_db->query($sql);
$gj_gj = $query->fetchColumn();
$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.t_guanjun where x_result is not null and match_type=1 and match_date=:match_date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$gj_jg = $stmt->fetchColumn();
$gj = $gj_gj + $gj_jg;
$sql = 'SELECT count(*) as s FROM mydata4_db.t_guanjun WHERE Match_CoverDate>now() and x_result is null and match_type=2';
$query = $mydata1_db->query($sql);
$jr_jr = $query->fetchColumn();
$params = array(':match_date' => $md);
$sql = 'SELECT count(*) as s FROM mydata4_db.t_guanjun where x_result is not null and match_type=2 and match_date=:match_date';
$stmt = $mydata1_db->prepare($sql);
$stmt->execute($params);
$jr_jg = $stmt->fetchColumn();
$jr = $jr_jr + $jr_jg;
if ($uid && (0 < $uid)){
	$params = array(':uid' => $uid);
	$sql = 'SELECT sum(bet_money) as s FROM `k_bet` where uid=:uid and status=0';
	$stmt = $mydata1_db->prepare($sql);
	$stmt->execute($params);
	$tz_money = $stmt->fetchColumn();
	$params = array(':uid' => $uid);
	$sql = 'select sum(bet_money) as s from k_bet_cg_group where uid=:uid and status=0';
	$stmt = $mydata1_db->prepare($sql);
	$stmt->execute($params);
	$tz_money += $stmt->fetchColumn();
	$params = array(':uid' => $uid);
	$sql = 'select count(*) as s from k_user_msg where uid=:uid and islook=0';
	$stmt = $mydata1_db->prepare($sql);
	$stmt->execute($params);
	$user_num = $stmt->fetchColumn();
	$params = array(':uid' => $uid);
	$sql = 'select money as s from k_user where uid=:uid limit 1';
	$stmt = $mydata1_db->prepare($sql);
	$stmt->execute($params);
	$user_money = sprintf('%.2f', $stmt->fetchColumn());
}
$json['zq'] = $zq;
$json['zq_ds'] = $zq_ds;
$json['zq_gq'] = $zq_gq;
$json['zq_sbc'] = $zq_sbc;
$json['zq_sbbd'] = $zq_sbbd;
$json['zq_bd'] = $zq_bd;
$json['zq_rqs'] = $zq_rqs;
$json['zq_bqc'] = $zq_bqc;
$json['zq_jg'] = $zq_jg;
$json['zqzc'] = $zqzc;
$json['zqzc_ds'] = $zqzc_ds;
$json['zqzc_sbc'] = $zqzc_sbc;
$json['zqzc_sbbd'] = $zqzc_sbbd;
$json['zqzc_bd'] = $zqzc_bd;
$json['zqzc_rqs'] = $zqzc_rqs;
$json['zqzc_bqc'] = $zqzc_bqc;
$json['lm'] = $lm;
$json['lm_ds'] = $lm_ds;
$json['lm_dj'] = $lm_dj;
$json['lm_gq'] = $lm_gq;
$json['lm_jg'] = $lm_jg;
$json['lmzc'] = $lmzc;
$json['lmzc_ds'] = $lmzc_ds;
$json['lmzc_dj'] = $lmzc_dj;
$json['wq'] = $wq;
$json['wq_ds'] = $wq_ds;
$json['wq_bd'] = $wq_bd;
$json['wq_jg'] = $wq_jg;
$json['pq'] = $pq;
$json['pq_ds'] = $pq_ds;
$json['pq_bd'] = $pq_bd;
$json['pq_jg'] = $pq_jg;
$json['bq'] = $bq;
$json['bq_ds'] = $bq_ds;
$json['bq_zdf'] = $bq_zdf;
$json['bq_jg'] = $bq_jg;
$json['gj'] = $gj;
$json['gj_gj'] = $gj_gj;
$json['gj_jg'] = $gj_jg;
$json['jr'] = $jr;
$json['jr_jr'] = $jr_jr;
$json['jr_jg'] = $jr_jg;
$json['tz_money'] = $tz_money . ' RMB';
$json['user_money'] = $user_money . ' RMB';
$json['user_num'] = $user_num;

echo $callback.'('.json_encode($json).')';
exit();